version: '3.7'

services:
    cod4:
        build: .
        # image: skrtheboss/cod4
        volumes:
            - /home/cod4-base/main:/home/user/cod4/main
            - /home/cod4-base/zone:/home/user/cod4/zone:ro
            - /home/cod4-base/mods:/home/user/cod4/mods
            - /home/cod4-base/usermaps:/home/user/cod4/usermaps:ro
            - /home/cod4-server-1:/home/user/.callofduty # Optional `.callofduty` is the default sv_homepath
            - /home/cod4-server-1/screenshots:/home/user/cod4/screenshots # Optional save screenshots on an external path
        ports:
            - 28963:28960/udp
        command: +set dedicated 2+exec server.cfg+map_rotate
        # Example of how to run with mods
        # command: +set dedicated 2+set fs_game mods/mod_name+exec server.cfg+map_rotate
        network_mode: bridge

    # Example of a fast-download configuration
    # Usermaps will be available under: http://fastdownload.your-domain.com/cod4/{mods, usermaps}/...
#    nginx-proxy:
#        image: jwilder/nginx-proxy
#        container_name: nginx-proxy
#        ports:
#            - "80:80"
#        volumes:
#            - /var/run/docker.sock:/tmp/docker.sock:ro
#        restart: always
#
#    fastdownload:
#        image: flashspys/nginx-static
#        container_name: fastdownload
#        expose:
#            - 80
#        volumes:
#            - /home/denis/cod4-base/mods:/static/cod4/mods:ro
#            - /home/denis/cod4-base/usermaps:/static/cod4/usermaps:ro
#        restart: always
#        environment:
#            - VIRTUAL_HOST=fastdownload.your-domain.com
#
#networks:
#    default:
#        external:
#            name: nginx-proxy
