#!/bin/bash

docker build --build-arg BUILD_DATE=`date -u +"%Y-%m-%dT%H:%M:%SZ"` \
             --build-arg VCS_REF=`git rev-parse --short HEAD` \
             --build-arg BUILD_VERSION=`git describe --tags $(git rev-list --tags --max-count=1)` \
             -t $IMAGE_NAME .
